# Generated by Django 5.1.5 on 2025-01-24 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pre_description', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('added_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('author', models.CharField(max_length=255)),
                ('author_position', models.CharField(max_length=255)),
            ],
        ),
    ]
