# Generated by Django 5.1.5 on 2025-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='postal_code',
            field=models.CharField(max_length=100),
        ),
    ]
