# Generated by Django 5.1.5 on 2025-01-25 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_connection_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
