# Generated by Django 5.1.5 on 2025-01-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('email_post', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='governance_photos/')),
            ],
        ),
    ]
