# Generated by Django 5.1.5 on 2025-01-26 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('working_hours', models.CharField(max_length=255)),
                ('first_phone', models.CharField(max_length=20)),
                ('second_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('embed_map_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('email_post', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='governance_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pre_description', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('author_position', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoQa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='news_qa.galleryqa')),
            ],
        ),
    ]
